### PR TITLE
Updates for Laravel 5 and Symfony 2.6

### PR DESCRIPTION
**Pull request by jszobody**
This updates the laravel-security package for Laravel 5 and also Symfony 2.6.

Specifically:
1. Updates service provider (Laravel 5 doesn't have a `$this->package()` method)
2. Changed config to be what I think Laravel 5 now prefers. (Publishing to a local config file, and then merging the local file on top of package file.)
3. Updated user interface (Auth\UserInterface -> Contracts\Auth\Authenticatable)
4. Removed deprecated SecurityContext and split out a TokenManager and AuthorizationChecker ([see here](http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements) for details)

I'm successfully using this updated package in a Laravel 5 app currently under development.

### CODE REVIEW

**Comment by barryvdh** [comment]
Ok looks cool. About those changes you linked, how does Symfony handle that? Should we still keep the old context as well, for easier upgrade?

**Comment by jszobody** [comment]
Laravel 5 now [requires symfony/security-core 2.6](https://github.com/laravel/framework/blob/5.0/composer.json#L35). And `SecurityContext` [now triggers a error](https://github.com/symfony/security-core/blob/master/SecurityContext.php#L14).

So no, I wouldn't keep it around. Anyone running Laravel 5 should have the new `TokenManager` and `AuthorizationChecker` available.

**Comment by barryvdh** [comment]
It triggers the error on dev-master/2.7, not on 2.6. And it only triggers it when people actually use it.

I based this mostly on the [Silex ServiceProvider](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SecurityServiceProvider.php) so I think it might be best to follow that.

So what do you think about:
- Renaming the AuthorizationChecker from `security.authorization_checker` to `security.authorization_checker`
-  Add the `SecurityContext` as `security`, mark as deprecated.
- point the Facade to `security.authorization_checker` instead of `security`

I could also live without the SecurityContext because this is just a 0.x package and I don't know how many people actually use the `security` key directly.. 
But regardless, perhaps it'sbetter to follow the container key names from Symfony/Silex anyways.

Could you also bump composer.json to php5.4, security-core 2.6 and laravel 5.0.x?
(And if you want, add a alias to dev-master for 0.2.x)

**Comment by jszobody** [comment]
Ah, that makes sense. Just updated my PR with those items, except for the composer alias (will have to read up on that, not familiar with it).

**Comment by jszobody** [comment]
Looks like the Readme will need updating in a number of places. I'm happy to help, just want to make sure this latest updated is what you had in mind first. Let me know if there's anything else you'd like to see here.

**Comment by barryvdh** [comment]
This is merged. I've added the branch alias, so you can require `0.2.x@dev` to test it. Also cleaned it up a bit (PSR-4, unused folders etc)

**Pull request merged**
